name: Build and Publish Extension

on:
  push:
    tags:
      - 'v*'  # Run when pushing version tags like v1.0.0

jobs:
  build:
    name: Build and Package Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create ZIP Package
        run: |
          mkdir -p build
          zip -r build/ufocus.zip manifest.json background.js popup.html popup.js

      - name: Upload ZIP as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ufocus
          path: build/ufocus.zip

  publish:
    name: Publish to Firefox AMO
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download the ZIP from Build
        uses: actions/download-artifact@v3
        with:
          name: ufocus
          path: build/

      - name: Publish to Firefox Add-ons (AMO)
        uses: kewisch/action-web-ext@v1
        with:
          apiKey: ${{ secrets.AMO_API_KEY }}
          apiSecret: ${{ secrets.AMO_API_SECRET }}
          source: build/ufocus.zip
          id: aa423535-b06f-42c3-9419-55ac62edb377@mozilla.org  # Replace with your extension's AMO ID
          channel: listed  # Use "unlisted" if publishing manually first

