name: Build and Publish Extension

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    name: Build and Package Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Extension
        id: web-ext-build
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: build
          source: .
          filename: "ufocus.zip"

      - name: Upload XPI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ufocus-extension
          path: ${{ steps.web-ext-build.outputs.target }}

  publish:
    name: Publish to Firefox AMO
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built XPI
        uses: actions/download-artifact@v4
        with:
          name: ufocus-extension
          path: build/

      - name: Publish to Firefox Add-ons (AMO)
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: sign
          source: build/ufocus.zip
          channel: listed  # Use "unlisted" if this is the first submission
          apiKey: ${{ secrets.AMO_API_KEY }}
          apiSecret: ${{ secrets.AMO_API_SECRET }}
          timeout: 900000  # 15 minutes

      - name: Attach Signed XPI to Release (Optional)
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            ${{ steps.web-ext-sign.outputs.target }}
